services:
  psql_monexa:
    container_name: psql_monexa
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume_monexa:/var/lib/postgresql/data

volumes:
  psql_volume_monexa:
